import { mkdir, rm } from 'node:fs/promises';

const directory = 'src/generated';
const output = `${directory}/novnc.js`;
await mkdir(directory, { recursive: true });

const tempEntry = `${directory}/entry.js`;
await Bun.write(tempEntry, `import RFB from '@novnc/novnc/lib/rfb.js';globalThis.RFB = RFB;`);

const result = await Bun.build({
  entrypoints: [tempEntry],
  format: 'iife',
  minify: true,
  naming: 'novnc.js',
  outdir: directory,
  target: 'browser',
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  await rm(tempEntry);
  process.exit(1);
}

const bundle = `/* Generated from @novnc/novnc. Do not edit. */\n${await Bun.file(output).text()}`;
await Bun.write(output, bundle);
await Bun.write(`${directory}/novnc_script.ts`, `// Generated by scripts/build-novnc.ts. Do not edit.\nexport default ${JSON.stringify(bundle)};\n`);
await rm(output);
await rm(tempEntry);
console.log(`Built ${output}`);
