import { mkdir, rm } from 'node:fs/promises';

const directory = 'src/generated';
const output = `${directory}/novnc.js`;
await mkdir(directory, { recursive: true });

const result = await Bun.build({
  entrypoints: ['node_modules/@novnc/novnc/lib/rfb.js'],
  minify: true,
  naming: 'novnc.js',
  outdir: directory,
  target: 'browser',
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

const bundle = `/* Generated from @novnc/novnc. Do not edit. */\n${await Bun.file(output).text()}\nwindow.RFB=NoVNC.default;\n`;
await Bun.write(output, bundle);
await Bun.write(`${directory}/novnc_base64.ts`, `// Generated by scripts/build-novnc.ts. Do not edit.\nexport default ${JSON.stringify(Buffer.from(bundle).toString('base64'))};\n`);
await rm(output);
console.log(`Built ${output}`);
