FROM oven/bun:latest

WORKDIR /app

# Copy client application source
COPY client/ /app/

# Install client dependencies
RUN bun install

EXPOSE 8081

ENV EXPO_PUBLIC_API_URL=https://localhost:18765

# Start Expo web client
CMD ["bun", "run", "web"]
